[build]
  publish = "public"
  command = "yarn run build"
[build.environment]
  YARN_VERSION = "1.7.0"
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "img-src 'self'; media-src 'self'"